import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

type SpringPlan = {profile:string;backend_root:string;frontend_root:string|null;build_tool:string;artifact:string;health_path:string;health_policy:string;adapter:string;service_hints:string[];services:Record<string,{enabled:boolean;mountPath?:string}>};
const springPresets=['SPRING_BOOT','SPRING_BOOT_JAR','SPRING_BOOT_VITE'];
const runtimePresets=['NODE_SERVER',...springPresets];
const isSpring=(preset:string)=>springPresets.includes(preset);
const springLabel=(preset:string)=>preset==='SPRING_BOOT_JAR'?'SPRING_BOOT_JAR · Java 21 · Gradle/Maven Wrapper · 실행 JAR':'SPRING_BOOT_VITE · Java 21 + Vite · 선택 서비스';
function PlanDetails({plan}:{plan?:SpringPlan|null}){return plan?<div className="plan-details"><p>백엔드 {plan.backend_root} · {plan.build_tool}{plan.frontend_root?` · 프런트엔드 ${plan.frontend_root}`:''}</p><p>JAR 선택: <code>{plan.artifact}</code> · 상태 확인: <code>{plan.health_path}</code></p><p>{plan.health_policy==='http-reachable'?'HTTP 연결 확인: 기본 /의 404를 허용합니다. 앱 기능 검증은 별도이며 health.path 지정 시 2xx를 요구합니다.':'상태 확인 경로에서 2xx 응답을 확인합니다.'}</p><p>관리 서비스: {Object.entries(plan.services).filter(([,v])=>v.enabled).map(([k])=>k).join(', ')||'없음'}{plan.service_hints.length?` · 의존성 힌트: ${plan.service_hints.join(', ')} (자동 생성 근거 아님)`:''}</p>{plan.adapter==='aurashop-v1'&&<p>기존 aurashop-v1 호환 처리 적용 · 배포 복사본 변경 내용은 로그에 기록됩니다.</p>}</div>:null;}
type Source = {plan?:SpringPlan|null;id:string;kind:string;locator:string;status:string;preset:string;sha:string;branch:string|null;error:string|null};
type Deployment = {settings?:{plan?:SpringPlan};id:string;source_id:string;status:string;preset:string;sha:string;created:number;stages:Record<string,number>;error:string|null;exit_code:number|null;preview_url:string;cancel:number;runtime_state:string|null;runtime_error:string|null;runtime_image:string|null;deployment_status:string;validation:{files:number;bytes:number}|null};
type Transition = {id:number;previous_id:string|null;deployment_id:string;kind:string;created:number};
type Project = {id:string;name:string;slug:string;preset:string;source_id:string;production_id:string|null;production_url:string;production_health:string|null;production_error:string|null;operations:{id:string;status:string;error:string|null}[];latest_status:string;latest_at:number;deleting:number;source:Source;deployments:Deployment[];transitions:Transition[]};
type Log = {id:number;text:string;stream:'build'|'runtime'};
let csrf = '';
const keys = new Map<string,string>();
async function api<T=any>(path:string, method='GET', body?:unknown):Promise<T> {
  const signature = method + path + (body instanceof File ? `${body.name}:${body.lastModified}:${body.size}` : JSON.stringify(body));
  const headers:Record<string,string> = {};
  if (method !== 'GET') { headers['X-CSRF-Token']=csrf; if(!keys.has(signature)) keys.set(signature,crypto.randomUUID()); headers['Idempotency-Key']=keys.get(signature)!; }
  if (body && !(body instanceof File)) headers['Content-Type']='application/json';
  const response = await fetch(path,{method,headers,body:body instanceof File ? body : body ? JSON.stringify(body) : undefined});
  const data = await response.json();
  if (!response.ok) {
    if (response.status === 401 && path !== '/api/login') window.dispatchEvent(new Event('session-expired'));
    if (response.status < 500) keys.delete(signature);
    throw new Error(typeof data.detail === 'string' ? data.detail : '입력 내용을 확인해 주세요.');
  }
  keys.delete(signature);
  return data;
}
const date = (n?:number|null) => n ? new Date(n*1000).toLocaleString('ko-KR',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'}) : '—';
const short = (s?:string|null) => s ? s.slice(0,8) : '—';
const active = (s:string) => ['QUEUED','FETCHING','BUILDING','PUBLISHING','STARTING','HEALTH_CHECK'].includes(s);
const labels:Record<string,string> = {QUEUED:'대기 중',FETCHING:'소스 준비',BUILDING:'빌드 중',STARTING:'서버 시작',HEALTH_CHECK:'응답 확인',UNAVAILABLE:'서버 복구 필요',PUBLISHING:'공개 검증',READY:'준비 완료',FAILED:'실패',CANCELED:'취소됨'};
function Badge({status}:{status:string}) {return <span className={'badge '+status.toLowerCase()}><i/>{labels[status]||status}</span>}
function External({url,children}:{url:string;children:React.ReactNode}) {return <a className="button" href={url} target="_blank" rel="noopener noreferrer">{children}<span aria-hidden>↗</span></a>}

function App(){
  const [logged,setLogged]=useState<boolean|null>(null), [password,setPassword]=useState('');
  const [projects,setProjects]=useState<Project[]>([]), [pid,setPid]=useState<string|null>(location.hash.slice(1)||null);
  const [project,setProject]=useState<Project|null>(null), [depId,setDepId]=useState<string|null>(null);
  const [logStream,setLogStream]=useState<'build'|'runtime'>('build');
  const [logs,setLogs]=useState<Log[]>([]), [modal,setModal]=useState<'new'|'update'|null>(null);
  const [error,setError]=useState(''), [notice,setNotice]=useState(''), [busy,setBusy]=useState(false), [worker,setWorker]=useState<boolean|null>(null);
  const actionPending=useRef(false);
  const [confirmation,setConfirmation]=useState<{title:string;message:string;label:string;run:()=>Promise<void>}|null>(null);
  const [cleanup,setCleanup]=useState<string|null>(null);
  const dep=depId ? project?.deployments.find(d=>d.id===depId) : project?.deployments[0];

  async function refresh(){
    const [list,health]=await Promise.all([api<Project[]>('/api/projects'),api('/api/health')]);setProjects(list);setWorker(health.worker_alive);
    if(pid)setProject(await api<Project>('/api/projects/'+pid));
  }
  useEffect(()=>{api('/api/session').then(s=>{csrf=s.csrf;setLogged(true)}).catch(()=>setLogged(false));
    const expired=()=>{csrf='';setLogged(false);setError('세션이 만료되었습니다. 다시 로그인하세요.')};
    const hash=()=>{setPid(location.hash.slice(1)||null);setDepId(null);setProject(null)};
    window.addEventListener('session-expired',expired);window.addEventListener('hashchange',hash);
    return()=>{window.removeEventListener('session-expired',expired);window.removeEventListener('hashchange',hash)};
  },[]);
  useEffect(()=>{if(!logged)return;let stopped=false,running=false;const poll=async()=>{if(running||stopped)return;running=true;try{await refresh()}catch(e){if(!stopped)setError((e as Error).message)}finally{running=false}};void poll();const timer=setInterval(poll,1200);return()=>{stopped=true;clearInterval(timer)}},[logged,pid]);
  useEffect(()=>{setLogs([]);if(!dep?.id)return;let stopped=false,cursor=0,running=false;const poll=async()=>{if(stopped||running)return;running=true;try{const result=await api<{items:Log[];cursor:number}>(`/api/deployments/${dep.id}/logs?cursor=${cursor}`);if(!stopped){cursor=result.cursor;setLogs(old=>[...old,...result.items])}}catch(e){if(!stopped)setError((e as Error).message)}finally{running=false}};void poll();const timer=setInterval(poll,1000);return()=>{stopped=true;clearInterval(timer)}},[dep?.id]);
  useEffect(()=>{if(!cleanup)return;const timer=setInterval(async()=>{try{const row=await api('/api/cleanup/'+cleanup);if(row.deleted){setNotice(row.cleanup);setCleanup(null);void refresh()}else if(row.cleanup?.includes('실패'))setError(row.cleanup)}catch(e){setError((e as Error).message)}},1000);return()=>clearInterval(timer)},[cleanup]);
  async function act(fn:()=>Promise<void>){if(actionPending.current)return;actionPending.current=true;setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{actionPending.current=false;setBusy(false)}}
  function go(id:string|null){setProject(null);setDepId(null);setPid(id);location.hash=id||'';setError('')}
  async function switchProduction(id:string,kind:string){const result=await api(`/api/projects/${pid}/production`,'POST',{deployment_id:id,kind});if(result.operation_id){setNotice('보존 이미지의 서버 응답을 확인하고 있습니다. 성공 후 운영 주소가 전환됩니다.');for(;;){await new Promise(resolve=>setTimeout(resolve,700));const op=await api('/api/operations/'+result.operation_id);if(op.status==='FAILED')throw new Error(op.error);if(op.status==='DONE')break;}}setNotice(kind==='rollback'?'이전 운영 버전으로 롤백했습니다. 사이트를 새로고침해 확인하세요.':'운영에 반영했습니다. 고정 URL을 열어 확인하세요.');await refresh()}
  const header=<header className="topbar"><button className="brand" onClick={()=>go(null)}><span className="brandmark">C<span>↗</span></span>Campus Deploy</button><span className="top-divider"/><span className="workspace">팀 워크스페이스</span><span className="top-spacer"/><span className="demo-chip">LOCAL · P1</span>{logged&&<><span className={'worker '+(worker?'online':'')}><i/>{worker===null?'연결 확인':worker?'워커 연결됨':'워커 연결 대기'}</span><button className="quiet" onClick={()=>void act(async()=>{await api('/api/logout','POST');setLogged(false);csrf=''})}>로그아웃</button><span className="avatar">C</span></>}</header>;
  if(logged===null)return <>{header}<main className="loading">관리 세션을 확인하고 있습니다.</main></>;
  if(!logged)return <>{header}<main className="login-layout"><section className="login-intro"><p className="eyebrow">FROM SOURCE TO SITE</p><h1>코드를 올리고,<br/>결과를 확인하세요.</h1><p>팀의 웹 사이트와 Node 서버를 배포하고<br/>Preview부터 운영, 롤백까지 관리합니다.</p><div className="support-chips"><span>HTML / CSS / JS</span><span>React + Vite</span><span>Node / Express</span></div></section><form className="login-card" onSubmit={e=>{e.preventDefault();void act(async()=>{const s=await api('/api/login','POST',{password});csrf=s.csrf;setPassword('');setLogged(true)})}}><span className="eyebrow">TEAM ACCESS</span><h2>관리자 로그인</h2><p>운영자가 준비한 단일 시험용 계정입니다.</p><label>관리자 암호<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required autoFocus/></label>{error&&<p role="alert" className="error">{error}</p>}<button className="primary wide" disabled={busy}>{busy?'로그인 중…':'워크스페이스 열기 →'}</button><small>초기 설정 시 저장된 관리자 암호를 사용하세요.</small></form></main></>;
  return <>{header}<div className="app-layout"><aside className="sidebar"><p className="nav-heading">워크스페이스</p><button className="nav-item selected" onClick={()=>go(null)}><span>▦</span> 프로젝트 <b>{projects.length}</b></button><div className="sidebar-bottom"><span className="eyebrow">지원 프리셋</span><strong>웹 사이트와 HTTP 서버</strong><p>STATIC · VITE_STATIC<br/>NODE_SERVER · Express<br/>SPRING_BOOT_JAR<br/>SPRING_BOOT_VITE</p><span className="side-note">팀 소스의 통제된 시연용</span></div></aside><main className="main-content">
    {error&&<div className="banner error" role="alert">{error}<button aria-label="오류 닫기" onClick={()=>setError('')}>×</button></div>}
    {notice&&<div className="banner success" role="status">{notice}<button aria-label="알림 닫기" onClick={()=>setNotice('')}>×</button></div>}
    {cleanup&&<div className="banner">라우트를 차단했습니다. 워커가 산출물과 작업 자원을 정리하고 있습니다.</div>}
    {!pid?<><div className="page-heading"><div><p className="eyebrow">WORKSPACE</p><h1>프로젝트</h1><p>소스에서 시작해, 운영 중인 사이트까지 한곳에서.</p></div><button className="primary" onClick={()=>setModal('new')}>＋ 새 프로젝트</button></div><div className="section-bar"><strong>모든 프로젝트 <span>{projects.length}</span></strong><span>최근 생성순</span></div>
      {projects.length===0?<section className="empty"><div className="empty-icon">＋</div><h2>첫 사이트를 배포해 보세요</h2><p>공개 GitHub 저장소 또는 ZIP 파일을 준비하세요.<br/>소스를 검사한 뒤 지원 프리셋을 알려드립니다.</p><button onClick={()=>setModal('new')}>프로젝트 만들기 →</button></section>:<div className="project-grid">{projects.map(p=><article className="project-card" key={p.id}><div className="card-title"><span className="project-symbol">{p.preset==='STATIC'?'◇':'⌘'}</span><button onClick={()=>go(p.id)}>{p.name}</button><span className="card-arrow">↗</span></div><div className="card-url">{p.production_id?<a href={p.production_url} target="_blank" rel="noopener noreferrer">{new URL(p.production_url).host} ↗</a>:<span>운영 배포 준비 중</span>}</div><div className="card-info"><span>{p.preset}</span>{p.deleting?<span className="badge canceled">삭제 중</span>:<Badge status={p.latest_status||'QUEUED'}/>}</div><footer><span>최근 배포</span><time>{date(p.latest_at)}</time></footer></article>)}</div>}
      <div className="scope-note"><span>i</span><p><strong>어떤 프로젝트를 배포할 수 있나요?</strong><br/>루트에 index.html이 있는 정적 사이트, 클라이언트 Vite, npm start와 package-lock.json을 포함한 Node HTTP, Java 21/Gradle + frontend/ Vite Spring Boot 프로젝트를 지원합니다.</p></div></>:
    !project?<p className="loading">프로젝트를 불러오고 있습니다.</p>:<>
      <button className="breadcrumb" onClick={()=>go(null)}>← 프로젝트 <span>/</span> {project.slug}</button>
      <div className="page-heading detail-heading"><div><p className="eyebrow">PROJECT</p><h1>{project.name}</h1><p>{project.preset} · {project.source.kind==='GIT'?project.source.locator:'ZIP으로 가져온 프로젝트'}</p></div><div className="actions"><button disabled={busy||!!project.deleting} onClick={()=>setModal('update')}>새 버전 배포</button>{project.production_id&&<External url={project.production_url}>운영 사이트 열기</External>}</div></div>
      <section className="production-card"><div className="production-icon">↗</div><div><p className="eyebrow">PRODUCTION</p><h2>{project.production_id?'현재 운영 중인 버전':'첫 성공 배포를 기다리고 있습니다'}</h2>{project.production_id&&<a href={project.production_url} target="_blank" rel="noopener noreferrer">{project.production_url} ↗</a>}<p>{project.production_id?`배포 ${short(project.production_id)} · 운영 전환은 이 주소에 즉시 반영됩니다.`:'첫 성공 배포는 자동으로 운영에 연결됩니다. 이후 배포는 Preview로 준비됩니다.'}</p></div>{project.production_id&&<span className={'badge '+(['READY','RUNNING'].includes(project.production_health||'')?'ready':'failed')}><i/>{['READY','RUNNING'].includes(project.production_health||'')?'운영 중':'서버 확인 필요'}</span>}</section>
      {project.deployments.some(d=>isSpring(d.preset))&&<div className="banner">Spring 롤백은 코드만 되돌리며 DB 데이터·스키마를 복원하지 않습니다. 관리 서비스를 사용하는 경우 Preview와 운영은 프로젝트 DB·Redis·저장소를 공유합니다. JAR 프로필은 manifest에서 선택한 서비스만 생성합니다.</div>}{project.production_error&&<div className="banner error">운영 복구 실패: {project.production_error}</div>}{project.operations?.filter(o=>o.status==='QUEUED'||o.status==='HEALTH_CHECK').map(o=><div className="banner" key={o.id}>운영 전환 대기 · 서버 응답 확인 중</div>)}{project.operations?.[0]?.status==='FAILED'&&<div className="banner error">최근 운영 전환 실패: {project.operations[0].error}</div>}
      <div className="detail-grid"><section className="history panel"><div className="panel-heading"><h2>배포 이력</h2><span>{project.deployments.length}개</span></div>{project.deployments.map(d=><button key={d.id} className={'deployment-row '+(dep?.id===d.id?'current':'')} onClick={()=>setDepId(d.id)}><div><code>{short(d.id)}</code>{d.id===project.production_id&&<span className="production-tag">운영</span>}<Badge status={d.status}/></div><p>{d.preset} · {short(d.sha)}</p><time>{date(d.created)}</time></button>)}</section>
      {dep&&<section className="deployment-detail panel"><div className="panel-heading"><div><p className="eyebrow">DEPLOYMENT</p><h2>배포 <code>{short(dep.id)}</code></h2></div><Badge status={dep.status}/></div><div className="deployment-actions"><button disabled={busy||!!project.deleting} onClick={()=>void act(async()=>{const d=await api(`/api/projects/${pid}/deployments`,'POST',{source_id:dep.source_id});setDepId(d.id);await refresh()})}>이 소스로 재배포</button>{dep.deployment_status==='READY'&&<><External url={dep.preview_url}>Preview 열기</External><button onClick={()=>void act(async()=>{await navigator.clipboard.writeText(dep.preview_url);setNotice('주소를 복사했습니다.')})}>주소 복사</button>{dep.id!==project.production_id&&<button className="primary" disabled={busy||!!project.deleting} onClick={()=>setConfirmation({title:'이 버전을 운영에 반영할까요?',message:`고정 운영 URL이 배포 ${short(dep.id)}를 제공하게 됩니다. 서버 응답 확인에 실패하면 현재 운영을 유지합니다.`,label:'운영 반영',run:()=>switchProduction(dep.id,'promote')})}>운영 반영</button>}</>}{active(dep.status)&&<button disabled={busy||!!dep.cancel} onClick={()=>setConfirmation({title:'이 배포를 취소할까요?',message:'진행 중인 작업과 임시 자원을 정리합니다. 현재 운영 사이트는 유지됩니다.',label:'배포 취소',run:async()=>{await api(`/api/deployments/${dep.id}/cancel`,'POST');await refresh()}})}>{dep.cancel?'취소 정리 대기':'배포 취소'}</button>}</div>
      <ol className="stages">{(runtimePresets.includes(dep.preset)?['QUEUED','FETCHING','BUILDING','STARTING','HEALTH_CHECK','READY']:['QUEUED','FETCHING','BUILDING','PUBLISHING','READY']).map(s=><li key={s} className={dep.stages[s]?'reached':''}><i>{dep.stages[s]?'✓':'·'}</i><strong>{labels[s]}</strong><span>{dep.stages[s]?date(dep.stages[s]):'—'}</span></li>)}</ol>
      {runtimePresets.includes(dep.preset)&&<div className="runtime-summary"><strong>{dep.runtime_state==='RUNNING'?'웹 서버 실행 중':dep.runtime_state==='STOPPED'?'서버 정지 · 이미지 보존':`웹 서버 상태: ${dep.runtime_state||'준비 중'}`}</strong>{dep.runtime_error&&<p className="error">{dep.runtime_error}</p>}{dep.runtime_image&&<p>보존 이미지 <code title={dep.runtime_image}>{dep.runtime_image.slice(0,24)}</code></p>}<small>PORT 8080 · 운영 반영/롤백 시 서버 응답을 다시 확인합니다.</small></div>}
      {dep.error&&<div className="deploy-error"><strong>{dep.status==='CANCELED'?'배포가 취소되었습니다':'배포를 완료하지 못했습니다'}</strong><p>{dep.error}</p>{dep.exit_code!==null&&<code>종료 코드 {dep.exit_code}</code>}</div>}
      <div className="build-meta"><span>소스 <code title={dep.sha}>{short(dep.sha)}</code></span><span>{dep.preset==='STATIC'?'빌드 없음 · 정적 파일 수집':isSpring(dep.preset)?(dep.preset==='SPRING_BOOT_JAR'?'Wrapper → 실행 JAR → Java':'Vite + Gradle → Java + 선택 서비스'):runtimePresets.includes(dep.preset)?'npm ci → 이미지 → npm start':'npm ci → npm run build → dist'}</span>{dep.validation&&<span>{dep.validation.files} files · {(dep.validation.bytes/1024).toFixed(1)} KiB</span>}</div>
      <PlanDetails plan={dep.settings?.plan}/><div className="log-heading"><strong>실행 로그</strong>{runtimePresets.includes(dep.preset)&&<div className="source-tabs"><button aria-pressed={logStream==='build'} onClick={()=>setLogStream('build')}>빌드 로그</button><button aria-pressed={logStream==='runtime'} onClick={()=>setLogStream('runtime')}>런타임 로그</button></div>}<span>{active(dep.status)?'실시간 갱신 · ':'저장된 로그 · '}새로고침 후에도 유지</span></div><pre className="logs" aria-label="실행 로그">{logs.length?logs.filter(log=>!runtimePresets.includes(dep.preset)||log.stream===logStream).map(log=><React.Fragment key={log.id}>{log.text.replace(/\x1b\[[0-9;]*m/g,'')}</React.Fragment>):'워커 실행을 기다리고 있습니다.'}</pre>
      </section>}</div>
      <section className="panel transitions"><div className="panel-heading"><h2>운영 전환 이력</h2><span>산출물을 다시 빌드하지 않습니다</span></div>{project.transitions.length?<table><thead><tr><th>작업</th><th>이전 버전</th><th>반영 버전</th><th>전환 시각</th><th>동작</th></tr></thead><tbody>{project.transitions.map(t=><tr key={t.id}><td>{t.kind==='rollback'?'롤백':'운영 반영'}</td><td><code>{short(t.previous_id)}</code></td><td><code>{short(t.deployment_id)}</code></td><td>{date(t.created)}</td><td>{t.deployment_id!==project.production_id?<button disabled={busy||!!project.deleting} onClick={()=>setConfirmation({title:'이 운영 버전으로 롤백할까요?',message:`고정 URL을 배포 ${short(t.deployment_id)}로 돌립니다. 빌드 없이 기존 산출물을 사용합니다. DB 데이터·스키마는 되돌리지 않습니다.`,label:'이 버전으로 롤백',run:()=>switchProduction(t.deployment_id,'rollback')})}>이 버전으로 롤백</button>:<span className="muted">현재 운영</span>}</td></tr>)}</tbody></table>:<p className="empty-small">아직 운영 전환 이력이 없습니다.</p>}</section>
      <footer className="danger-zone"><p><strong>프로젝트 삭제</strong><span>운영·Preview 주소와 산출물을 제거합니다. Spring DB·Redis·업로드 데이터도 삭제됩니다.</span></p><button className="danger" disabled={busy||!!project.deleting} onClick={()=>setConfirmation({title:`${project.name} 프로젝트를 삭제할까요?`,message:'운영·Preview 라우트와 산출물·작업 자원을 삭제합니다. Spring 프로젝트의 MySQL·Redis 데이터와 업로드 파일도 영구 삭제됩니다. 다른 프로젝트는 유지됩니다. 이 작업은 되돌릴 수 없습니다.',label:'프로젝트 삭제',run:async()=>{await api('/api/projects/'+pid,'DELETE');setCleanup(pid);go(null)}})}>프로젝트 삭제</button></footer>
    </>}
    <footer className="page-footer"><span>Campus Deploy</span><span>정적 · Node · Spring Boot · 팀 시연 환경</span></footer>
  </main></div>
  {modal&&<SourceModal project={modal==='update'?project:null} onClose={()=>setModal(null)} onCreated={(projectId,deploymentId)=>{setModal(null);setPid(projectId);location.hash=projectId;setDepId(deploymentId);setNotice('배포를 대기열에 등록했습니다. 실제 진행 상태와 로그를 확인하세요.') }}/>}
  {confirmation&&<div className="modal-backdrop" onClick={()=>!busy&&setConfirmation(null)}><section className="modal confirm" role="dialog" aria-modal="true" aria-labelledby="confirm-title" onClick={e=>e.stopPropagation()}><p className="eyebrow">확인</p><h2 id="confirm-title">{confirmation.title}</h2><p>{confirmation.message}</p><div className="actions"><button disabled={busy} onClick={()=>setConfirmation(null)}>돌아가기</button><button className="primary" disabled={busy} onClick={()=>void act(async()=>{await confirmation.run();setConfirmation(null)})}>{busy?'처리 중…':confirmation.label}</button></div></section></div>}
  </>;
}

function SourceModal({project,onClose,onCreated}:{project:Project|null;onClose:()=>void;onCreated:(pid:string,dep:string)=>void}){
  const [kind,setKind]=useState<'ZIP'|'GIT'>(project?.source.kind==='ZIP'?'ZIP':'GIT');
  const [name,setName]=useState(''),[slug,setSlug]=useState(''),[url,setUrl]=useState(project?.source.kind==='GIT'?project.source.locator:'');
  const [file,setFile]=useState<File|null>(null),[source,setSource]=useState<Source|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const sourceId=source?.id;
  const edited=useRef({name:false,slug:false}), slugSuffix=useRef(crypto.randomUUID().slice(0,6));
  function changeGitUrl(value:string){
    setUrl(value);setSource(null);
    if(project)return;
    try{
      const parsed=new URL(value.trim()),parts=parsed.pathname.split('/').filter(Boolean);
      if(parsed.protocol!=='https:'||parsed.hostname!=='github.com'||parts.length!==2)return;
      const repository=parts[1].replace(/\.git$/i,'');
      if(!edited.current.name)setName(repository.slice(0,80));
      const base=repository.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,32).replace(/-+$/,'')||'site';
      if(!edited.current.slug)setSlug(base+'-'+slugSuffix.current);
    }catch{/* An incomplete URL is validated when the user submits it. */}
  }
  useEffect(()=>{if(!sourceId||!source||['READY','FAILED'].includes(source.status))return;let stopped=false;const timer=setInterval(async()=>{try{const s=await api<Source>('/api/sources/'+sourceId);if(!stopped)setSource(s)}catch(e){if(!stopped)setError((e as Error).message)}},800);return()=>{stopped=true;clearInterval(timer)}},[sourceId,source?.status]);
  async function inspect(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const result=kind==='ZIP'?await api<Source>('/api/sources/zip','POST',file):await api<Source>('/api/sources/git','POST',{url:url.trim()});setSource(result)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function deploy(){if(busy||!source)return;setBusy(true);setError('');try{if(project){const d=await api(`/api/projects/${project.id}/deployments`,'POST',{source_id:source.id});onCreated(project.id,d.id)}else{const p=await api('/api/projects','POST',{name,slug,source_id:source.id});onCreated(p.id,p.deployment_id)}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <div className="modal-backdrop"><section className="modal source-modal" role="dialog" aria-modal="true" aria-labelledby="source-title"><div className="modal-top"><div><p className="eyebrow">{project?'NEW DEPLOYMENT':'NEW PROJECT'}</p><h2 id="source-title">{project?'새 버전 배포':'새 프로젝트 만들기'}</h2></div><button className="close" aria-label="닫기" onClick={onClose} disabled={busy}>×</button></div><p className="modal-desc">소스를 가져오면 지원 여부와 배포 프리셋을 확인합니다.</p>
  {!project&&<div className="form-row"><label>프로젝트 이름<input autoFocus={kind==='ZIP'} value={name} onChange={e=>{edited.current.name=!!e.target.value;setName(e.target.value)}} placeholder={kind==='GIT'?'GitHub 주소에서 자동 입력':'예: Campus Garden'} maxLength={80}/></label><label>프로젝트 주소 (slug)<input value={slug} onChange={e=>{edited.current.slug=!!e.target.value;setSlug(e.target.value.toLowerCase())}} placeholder={kind==='GIT'?'자동 생성 · 직접 수정 가능':'campus-garden'} maxLength={40}/></label></div>}
  <div className="source-tabs"><button aria-pressed={kind==='GIT'} className={kind==='GIT'?'active':''} onClick={()=>{setKind('GIT');setSource(null)}} disabled={busy}>공개 GitHub</button><button aria-pressed={kind==='ZIP'} className={kind==='ZIP'?'active':''} onClick={()=>{setKind('ZIP');setSource(null)}} disabled={busy}>ZIP 업로드</button></div>
  <form onSubmit={inspect}>{kind==='ZIP'?<label className="upload-zone"><span className="upload-icon">↑</span><strong>{file?file.name:'프로젝트 ZIP을 선택하세요'}</strong><span>최대 50MiB · 하나의 감싸는 폴더는 자동 정규화</span><input type="file" accept=".zip,application/zip" aria-label="프로젝트 ZIP" onChange={e=>{setFile(e.target.files?.[0]||null);setSource(null)}} required/></label>:<label>GitHub 저장소 주소<input aria-label="GitHub 저장소 주소" autoFocus type="url" value={url} onChange={e=>changeGitUrl(e.target.value)} placeholder="https://github.com/owner/repository" required/><small>공개 저장소 주소를 붙여넣고 소스 검사 → 배포하기를 누르세요. 이름과 주소는 자동 입력되며 GitHub 로그인이나 ZIP 파일은 필요하지 않습니다.</small></label>}<button className="wide inspect-button" disabled={busy||!!source&&active(source.status)||kind==='ZIP'&&!file}>{busy?'전송 중…':source&&active(source.status)?'소스 검사 중…':'소스 검사'}</button></form>
  {source&&<div className={'source-result '+(source.status==='FAILED'?'failed':'')}><div><strong>{source.status==='READY'?'지원되는 프로젝트입니다':source.status==='FAILED'?'지원 여부 검사 실패':'워커가 소스를 검사하고 있습니다'}</strong><Badge status={source.status}/></div>{source.status==='READY'&&<><p>{source.preset==='STATIC'?'STATIC · 빌드 없이 정적 파일 제공':isSpring(source.preset)?springLabel(source.preset):source.preset==='NODE_SERVER'?'NODE_SERVER · npm ci → 이미지 → npm start':'VITE_STATIC · npm ci → npm run build → dist'}</p><PlanDetails plan={source.plan}/><code>{source.branch?`${source.branch} · `:''}{short(source.sha)}</code></>}{source.error&&<p role="alert">{source.error}</p>}</div>}
  <div className="support-box"><strong>현재 지원 범위</strong><p>루트 index.html이 있는 정적 사이트 또는 package-lock.json을 포함한 클라이언트 Vite 프로젝트.<br/>Node/Express는 npm start, package-lock.json, process.env.PORT 및 0.0.0.0 listen이 필요합니다. 포트는 자동 설정됩니다.<br/>Spring Boot JAR는 Java 21 및 Gradle/Maven Wrapper를 지원하며 frontend가 필요하지 않습니다. 별도 Vite 화면도 지원합니다. JAR의 MySQL·Redis·저장소는 campus-deploy.yaml에서 선택합니다. Python·WAR·멀티모듈·WebSocket·cron·Next.js SSR·pnpm/yarn은 미지원입니다.</p></div>{error&&<p className="error" role="alert">{error}</p>}<div className="modal-footer"><span>{project?'운영은 유지되며 Preview로 준비됩니다.':'첫 성공 배포는 자동으로 운영됩니다.'}</span><button className="primary" disabled={busy||source?.status!=='READY'||!project&&(!name||!slug)} onClick={()=>void deploy()}>{busy?'등록 중…':'배포하기 →'}</button></div>
  </section></div>;
}

createRoot(document.getElementById('root')!).render(<App/>);
